spring:
  profiles:
    active: dev
---
server:
  port: 6001
spring:
  profiles: dev
  application:
    name: ms-config-eureka

eureka:
  instance:
    hostname: eureka6001.com
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://127.0.0.1:6001/eureka/
  server:
    enable-self-preservation: false
---
server:
  port: 6001
spring:
  profiles: dev
  application:
    name: ms-config-eureka

eureka:
  instance:
    hostname: eureka6001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:6001/eureka/
   server:
     enable-self-preservation: true
   