spring:
  profiles:
    active: dev
---
server:
  port: 8001
mybatis:
  config-location: classpath:/mybatis-cfg.xml
  type-aliases-package: com.lpp.entities
  mapper-locations: classpath:/mapper/**/*.xml
spring:
  profiles: dev
  application:
    name: ms-product-config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db01?serverTimezone=GMT%2B8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http:/127.0.0.1:6001/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
---
server:
  port: 8001
mybatis:
  config-location: classpath:/mybatis-cfg.xml
  type-aliases-package: com.lpp.entities
  mapper-locations: classpath:/mapper/*.xml
spring:
  profiles: prod
  application:
    name: ms-product-config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db02?serverTimezone=GMT%2B8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http:/127.0.0.1:6001/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true